import smtplib
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import date
from agent.models import Conference

logger = logging.getLogger(__name__)


def _fmt(d: date | None) -> str:
    return d.strftime("%Y-%m-%d") if d else "—"


def _relevance_bar(score: int) -> str:
    filled = round(score / 2)
    return "█" * filled + "░" * (5 - filled) + f" {score}/10"


def build_html_table(conferences: list[Conference]) -> str:
    rows = ""
    for c in conferences:
        rows += f"""
        <tr>
          <td><a href="{c.url}">{c.acronym} {c.year}</a></td>
          <td>{c.name}</td>
          <td>{_fmt(c.abstract_deadline)}</td>
          <td>{_fmt(c.full_paper_deadline)}</td>
          <td>{_fmt(c.camera_ready_deadline)}</td>
          <td>{_fmt(c.conference_date)}</td>
          <td>{c.venue or '—'}</td>
          <td style="font-size:0.85em;color:#555">{c.relevance_reason}</td>
        </tr>"""

    return f"""
<!DOCTYPE html>
<html>
<head>
<style>
  body {{ font-family: Arial, sans-serif; font-size: 14px; color: #222; }}
  h2 {{ color: #1a73e8; }}
  table {{ border-collapse: collapse; width: 100%; }}
  th {{ background: #1a73e8; color: white; padding: 8px 10px; text-align: left; }}
  td {{ padding: 7px 10px; border-bottom: 1px solid #ddd; vertical-align: top; }}
  tr:nth-child(even) {{ background: #f8f8f8; }}
  a {{ color: #1a73e8; text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  .footer {{ margin-top: 20px; font-size: 12px; color: #888; }}
</style>
</head>
<body>
  <h2>📅 Conference Deadlines — Weekly Report</h2>
  <p>Found <strong>{len(conferences)}</strong> relevant conferences for your PhD thesis
  (imbalanced learning, mixed-type tabular data).</p>

  <table>
    <thead>
      <tr>
        <th>Conference</th>
        <th>Full Name</th>
        <th>Abstract</th>
        <th>Paper Deadline</th>
        <th>Camera Ready</th>
        <th>Conference Date</th>
        <th>Venue</th>
        <th>Why Relevant</th>
      </tr>
    </thead>
    <tbody>{rows}
    </tbody>
  </table>

  <div class="footer">
    Generated by conference_agent (automated) · Sorted by relevance score
  </div>
</body>
</html>"""


def send_conference_email(
    conferences: list[Conference],
    to_addr: str,
    from_addr: str,
    app_password: str,
) -> None:
    if not conferences:
        logger.info("No conferences to email.")
        return

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Conference Deadlines Report — {len(conferences)} found"
    msg["From"] = from_addr
    msg["To"] = to_addr

    html = build_html_table(conferences)
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
        smtp.login(from_addr, app_password)
        smtp.sendmail(from_addr, to_addr, msg.as_string())

    logger.info(f"Email sent to {to_addr} with {len(conferences)} conferences.")
